# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: SpacyNLP
    model: 'en_core_web_trf'
  - name: SpacyTokenizer
    intent_tokenization_flag: True
    intent_split_symbol: "+"
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 150
    constrain_similarities: true
  # - name: FallbackClassifier
  #   threshold: 0.3
  #   ambiguity_threshold: 0.1
  - name: "DucklingEntityExtractor"
    # url of the running duckling server
    url: "http://localhost:8000"
    # dimensions to extract
    timezone: "Europe/Berlin"
    dimensions: ["time"]
    timeout : 3

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.7
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: TEDPolicy
    max_history: 5
    epochs: 150
    constrain_similarities: true
